export enum ApiErrorCode{
    INVALID_DATA = "INVALID_DATA",
    SENDING_EMAIL = "SENDING_EMAIL",
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
    UNAUTHORIZED = "UNAUTHORIZED"
}
