spring.application.name=games-price-tracker
#steam.web.api.store-app-list-url = https://api.steampowered.com/IStoreService/GetAppList/v1/?key=${STEAM_API_KEY}
some.steam.data.path=classpath:some-steam-data.json