# db
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:db/schema.sql

server.forward-headers-strategy=FRAMEWORK
server.port=${PORT:8080}

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false

steam.store.baseUrl=https://store.steampowered.com
steam.store.appUrl=${steam.store.baseUrl}/app/{id}/{name}
steam.store.appImgUrl=https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/{appId}/header.jpg
steam.api.applist.url=https://api.steampowered.com/IStoreService/GetAppList/v1/?key=${STEAM_API_KEY}
steam.api.appdetails.url=${steam.store.baseUrl}/api/appdetails
steam.api.appdetails.delay-between-requests=2s
steam.api.appdetails.max-pages-per-enqueue=${MAX_PAGES_PER_ENQUEUE}

price.min-interval-update=4d

app.email=${EMAIL_FROM}

account.sign-in-code-email-interval=2m

app.admin.key=${ADMIN_KEY}

app.client.url=${CLIENT_URL}