# db
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

steam.store.baseUrl=https://store.steampowered.com
steam.store.appUrl=${steam.store.baseUrl}/app/{id}/{name}
steam.store.appImgUrl=https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/{appId}/header.jpg
steam.api.applist.url=https://api.steampowered.com/IStoreService/GetAppList/v1/?key=${STEAM_API_KEY}
steam.api.appdetails.url=http://localhost:8080/api/appdetails
steam.api.appdetails.delay-between-requests=2s
steam.api.appdetails.games-per-request=20
steam.api.appdetails.max-pages-per-enqueue=3

price.min-interval-update=3d

# app email
app.email.sign-in-code-interval = 1m
app.email.from=mail@test.com

app.admin.key=dev-admin-key

app.client.url=http://localhost:4200

# spring mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mail@test.com

spring.thymeleaf.check-template-location=false

# habilita el control por parte de spring del header X-Forwarded-For 
server.forward-headers-strategy=FRAMEWORK 