# db
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=ALWAYS
spring.sql.init.schema-locations=classpath*:db/schema.sql

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=3000
spring.mail.properties[mail.smtp.writetimeout]=5000
spring.mail.properties[mail.smtp.auth]=true
spring.mail.properties[mail.smtp.starttls.enable]=true

spring.jpa.open-in-view=false
server.forward-headers-strategy=FRAMEWORK 
spring.thymeleaf.check-template-location=false

steam.store.baseUrl=https://store.steampowered.com
steam.store.appUrl=${steam.store.baseUrl}/app/{id}/{name}
steam.store.appImgUrl=https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/{appId}/header.jpg
steam.api.applist.url=https://api.steampowered.com/IStoreService/GetAppList/v1/?key=${STEAM_API_KEY}
steam.api.appdetails.url=${steam.store.baseUrl}/api/appdetails
steam.api.appdetails.delay-between-requests=2s
steam.api.appdetails.games-per-request=20
steam.api.appdetails.max-pages-per-enqueue=4

price.min-interval-update=4d

# app email
app.email.sign-in-code-interval = 2m
app.email.from=${EMAIL_FROM}

app.admin.key=${ADMIN_KEY}

app.client.url=${CLIENT_URL}