CREATE TABLE IF NOT EXISTS game(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    steam_id bigint NOT NULL UNIQUE,
    search_name varchar(255) NOT NULL,
    active boolean DEFAULT true
);

CREATE INDEX IF NOT EXISTS game_search_name_index ON game (search_name);

CREATE TABLE IF NOT EXISTS price(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    initial_price integer NOT NULL,
    final_price integer NOT NULL,
    created_at timestamptz NOT NULL,
    last_update timestamptz NOT NULL,
    game_id bigint REFERENCES game
);

CREATE TABLE IF NOT EXISTS account(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL UNIQUE,
    sign_in_code varchar(6),
    sign_in_code_expected_expiration timestamptz,
    last_sign_in_code_sent_at timestamptz
);

CREATE TABLE IF NOT EXISTS price_change_alert(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL,
    account_id bigint REFERENCES account,
    game_id bigint REFERENCES game
);

CREATE TABLE IF NOT EXISTS session_token(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token uuid NOT NULL UNIQUE,
    expiration timestamptz NOT NULL,
    account_id bigint NOT NULL REFERENCES account
);